"""Rewrite FP64 hotspots using the Ozaki Scheme.

Strategy:
  - For DGEMM calls: wrap with ozIMMU dgemm (same signature, drop-in).
  - For dense triple-nested loops: replace with ozIMMU DGEMM after converting
    the loop body to a GEMM call pattern.
  - Writes a companion 'ozaki_wrapper.f90' (or .c) alongside modified files.
  - Inserts #include / USE statements for the wrapper.

The rewrite is intentionally conservative: it only touches the identified
hotspot region and leaves everything else intact.
"""

import re
import shutil
from pathlib import Path

from .analyzer import Hotspot

# ── Ozaki DGEMM wrapper (Fortran) ─────────────────────────────────────────────

_OZAKI_F90_WRAPPER = """\
! ozaki_wrapper.f90 — thin Fortran interface to ozIMMU DGEMM
! Generated by try-ozaki.
module ozaki_wrapper
  use iso_c_binding
  implicit none

  interface
    ! ozIMMU: drop-in replacement for DGEMM using INT8 Tensor Core emulation
    subroutine ozimmu_dgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc) &
        bind(c, name="ozimmu_dgemm_wrapper")
      import :: c_char, c_int, c_double
      character(kind=c_char), intent(in) :: transa, transb
      integer(c_int), value :: m, n, k, lda, ldb, ldc
      real(c_double), value :: alpha, beta
      real(c_double), intent(in)  :: A(lda,*), B(ldb,*)
      real(c_double), intent(inout) :: C(ldc,*)
    end subroutine
  end interface

contains

  ! Convenience wrapper matching DGEMM signature exactly
  subroutine ozaki_dgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
    character, intent(in) :: transa, transb
    integer, intent(in) :: m, n, k, lda, ldb, ldc
    double precision, intent(in) :: alpha, beta
    double precision, intent(in)  :: A(lda,*), B(ldb,*)
    double precision, intent(inout) :: C(ldc,*)
    call ozimmu_dgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
  end subroutine

end module ozaki_wrapper
"""

# ── C wrapper header ───────────────────────────────────────────────────────────

_OZAKI_C_HEADER = """\
/* ozaki_wrapper.h — generated by try-ozaki */
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

/* Drop-in replacement for cblas_dgemm using ozIMMU */
void ozaki_dgemm(char transa, char transb, int m, int n, int k,
                 double alpha, const double *A, int lda,
                 const double *B, int ldb,
                 double beta, double *C, int ldc);

#ifdef __cplusplus
}
#endif
"""

# ── C shim source ─────────────────────────────────────────────────────────────

_OZAKI_C_SHIM = """\
/* ozaki_wrapper.c — generated by try-ozaki */
#include "ozaki_wrapper.h"
#include <ozIMMU/ozIMMU.h>

void ozaki_dgemm(char transa, char transb, int m, int n, int k,
                 double alpha, const double *A, int lda,
                 const double *B, int ldb,
                 double beta, double *C, int ldc) {
    /* Delegate to ozIMMU high-level DGEMM */
    ozimmu_dgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc);
}
"""


def _write_wrapper_once(dest_dir: Path, lang: str) -> None:
    if lang == "fortran":
        out = dest_dir / "ozaki_wrapper.f90"
        if not out.exists():
            out.write_text(_OZAKI_F90_WRAPPER)
    else:
        for name, content in [("ozaki_wrapper.h", _OZAKI_C_HEADER),
                               ("ozaki_wrapper.c", _OZAKI_C_SHIM)]:
            out = dest_dir / name
            if not out.exists():
                out.write_text(content)


def _add_use_statement(lines: list[str], module: str) -> list[str]:
    """Insert 'use <module>' after the first 'implicit none' or program/subroutine/function line."""
    for i, line in enumerate(lines):
        if re.match(r"^\s*implicit\s+none\b", line, re.IGNORECASE):
            lines.insert(i, f"  use {module}\n")
            return lines
    for i, line in enumerate(lines):
        if re.match(r"^\s*(program|subroutine|function|module)\b", line, re.IGNORECASE):
            lines.insert(i + 1, f"  use {module}\n")
            return lines
    lines.insert(0, f"  use {module}\n")
    return lines


def _rewrite_fortran_dgemm(lines: list[str], hotspot: Hotspot) -> list[str]:
    """Replace CALL DGEMM(...) with CALL OZAKI_DGEMM(...)."""
    ln = hotspot.start_line - 1  # 0-indexed
    original = lines[ln]
    replaced = re.sub(r"\bDGEMM\s*\(", "OZAKI_DGEMM(", original, flags=re.IGNORECASE)
    lines[ln] = replaced
    lines = _add_use_statement(lines, "ozaki_wrapper")
    return lines


def _rewrite_fortran_loop(lines: list[str], hotspot: Hotspot) -> list[str]:
    """Replace a triple-nested FP64 DO loop with an ozIMMU DGEMM call.

    This is a best-effort transformation: we comment out the loop body and
    inject a DGEMM call.  For more complex cases a note is left for the user.
    """
    s = hotspot.start_line - 1
    e = hotspot.end_line  # exclusive (0-indexed end+1)

    # Extract loop variables and array names from the body
    body = "".join(lines[s:e])

    # Try to detect loop variables i,j,k and arrays A,B,C
    do_match = re.findall(r"do\s+(\w+)\s*=\s*1\s*,\s*(\w+)", body, re.IGNORECASE)
    acc_match = re.search(
        r"(\w+)\s*\(([^)]+)\)\s*=\s*\1\s*\(([^)]+)\)\s*\+\s*(\w+)\s*\(([^)]+)\)\s*\*\s*(\w+)\s*\(",
        body, re.IGNORECASE,
    )

    comment_block = ["! [try-ozaki] Original FP64 triple-nested loop — replaced by Ozaki DGEMM\n"]
    for line in lines[s:e]:
        comment_block.append("!" + line)

    if do_match and len(do_match) >= 3 and acc_match:
        c_arr = acc_match.group(1)
        a_arr = acc_match.group(4)
        b_arr = acc_match.group(6)
        dims = {v.lower(): dim for v, dim in do_match}
        n_var = list(dims.values())[0] if dims else "N"

        ozaki_call = [
            "! [try-ozaki] Ozaki DGEMM replacement (FP64 emulated via INT8 Tensor Cores)\n",
            f"  call OZAKI_DGEMM('N','N',{n_var},{n_var},{n_var},"
            f"1.0d0,{a_arr},size({a_arr},1),{b_arr},size({b_arr},1),"
            f"0.0d0,{c_arr},size({c_arr},1))\n",
        ]
    else:
        ozaki_call = [
            "! [try-ozaki] TODO: manual DGEMM replacement needed here\n",
            "! Loop pattern too complex for automatic extraction.\n",
        ]

    lines[s:e] = comment_block + ozaki_call
    lines = _add_use_statement(lines, "ozaki_wrapper")
    return lines


def _rewrite_c_dgemm(lines: list[str], hotspot: Hotspot) -> list[str]:
    ln = hotspot.start_line - 1
    original = lines[ln]
    replaced = re.sub(r"\bcblas_dgemm\s*\(", "ozaki_dgemm(", original)
    replaced = re.sub(r"\bDGEMM\s*\(", "ozaki_dgemm(", replaced, flags=re.IGNORECASE)
    lines[ln] = replaced
    # Ensure header is included
    has_include = any("ozaki_wrapper.h" in l for l in lines)
    if not has_include:
        lines.insert(0, '#include "ozaki_wrapper.h"\n')
    return lines


def rewrite(repo_dir: Path, hotspots: list[Hotspot]) -> list[Path]:
    """Apply Ozaki rewrites to all detected hotspots.

    Modifies files in-place (repo_dir should be a copy/clone).
    Returns list of modified file paths.
    """
    modified: set[Path] = set()
    written_wrappers: set[str] = set()

    # Group by file so we process line edits in order (bottom-up to preserve line numbers)
    from collections import defaultdict
    by_file: dict[Path, list[Hotspot]] = defaultdict(list)
    for h in hotspots:
        by_file[h.file].append(h)

    for file_path, hs in by_file.items():
        # Sort hotspots bottom-up so line number edits don't shift later ones
        hs_sorted = sorted(hs, key=lambda h: h.start_line, reverse=True)
        lines = file_path.read_text(errors="replace").splitlines(keepends=True)

        for h in hs_sorted:
            lang = h.language
            if lang == "fortran":
                if h.kind == "dgemm_call":
                    lines = _rewrite_fortran_dgemm(lines, h)
                elif h.kind == "loop_nest":
                    lines = _rewrite_fortran_loop(lines, h)
            elif lang in ("c", "cpp"):
                if h.kind in ("dgemm_call", "dgemv_call"):
                    lines = _rewrite_c_dgemm(lines, h)

            if lang not in written_wrappers:
                _write_wrapper_once(file_path.parent, lang)
                written_wrappers.add(lang)

        file_path.write_text("".join(lines))
        modified.add(file_path)

    return sorted(modified)
