"""Rewrite FP64 hotspots using the Ozaki Scheme.

Strategy:
  - For DGEMM calls: wrap with ozIMMU dgemm (same signature, drop-in).
  - For dense triple-nested loops: replace with ozIMMU DGEMM after converting
    the loop body to a GEMM call pattern.
  - Writes a companion 'ozaki_wrapper.f90' (or .c) alongside modified files.
  - Inserts #include / USE statements for the wrapper.

The rewrite is intentionally conservative: it only touches the identified
hotspot region and leaves everything else intact.
"""

import re
import shutil
from pathlib import Path

from .analyzer import Hotspot

# ── Ozaki DGEMM wrapper (Fortran) ─────────────────────────────────────────────

_OZAKI_F90_WRAPPER = """\
! ozaki_wrapper.f90 — thin Fortran interface to ozIMMU DGEMM
! Generated by try-ozaki.
!
! Calling convention: Fortran passes all arguments by reference.
! The C shim (ozaki_wrapper.cpp) receives pointers and dereferences them.
module ozaki_wrapper
  use iso_c_binding
  implicit none

  interface
    ! Maps to extern "C" void ozimmu_dgemm_wrapper(...) in ozaki_wrapper.cpp
    subroutine ozimmu_dgemm_c(transa, transb, m, n, k, alpha, A, lda, &
                               B, ldb, beta, C, ldc) &
        bind(c, name="ozimmu_dgemm_wrapper")
      import :: c_char, c_int, c_double
      ! All args passed by reference (Fortran default, C receives pointers)
      character(kind=c_char), intent(in) :: transa, transb
      integer(c_int), intent(in) :: m, n, k, lda, ldb, ldc
      real(c_double), intent(in)  :: alpha, beta
      real(c_double), intent(in)  :: A(lda,*), B(ldb,*)
      real(c_double), intent(inout) :: C(ldc,*)
    end subroutine
  end interface

contains

  ! Drop-in for DGEMM: C = alpha*A*B + beta*C
  subroutine ozaki_dgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
    character, intent(in) :: transa, transb
    integer, intent(in) :: m, n, k, lda, ldb, ldc
    double precision, intent(in) :: alpha, beta
    double precision, intent(in)  :: A(lda,*), B(ldb,*)
    double precision, intent(inout) :: C(ldc,*)
    call ozimmu_dgemm_c(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
  end subroutine

end module ozaki_wrapper
"""

# ── C shim source (C++ because ozIMMU is a C++ namespace API) ─────────────────
# Exposed as extern "C" so Fortran bind(c, name="ozimmu_dgemm_wrapper") finds it.
# Uses fp64_int8_auto mode which picks the minimum slice count for exact FP64.

_OZAKI_C_SHIM = """\
/* ozaki_wrapper.c — generated by try-ozaki
 * Implements the C symbol that ozaki_wrapper.f90 calls via bind(c).
 * Must be compiled as C++ (ozIMMU is a C++ API). */
#include <cuda_runtime.h>     /* must come before ozimmu.hpp to define cudaStream_t */
#include <ozimmu/ozimmu.hpp>
#include <cstring>

extern "C" {

/* Fortran passes ALL arguments by reference — every parameter is a pointer. */
void ozimmu_dgemm_wrapper(
    const char *transa, const char *transb,
    const int *m_p, const int *n_p, const int *k_p,
    const double *alpha,
    const double *A, const int *lda_p,
    const double *B, const int *ldb_p,
    const double *beta,
    double *C, const int *ldc_p)
{
    const std::size_t m   = (std::size_t)(*m_p);
    const std::size_t n   = (std::size_t)(*n_p);
    const std::size_t k   = (std::size_t)(*k_p);
    const std::size_t lda = (std::size_t)(*lda_p);
    const std::size_t ldb = (std::size_t)(*ldb_p);
    const std::size_t ldc = (std::size_t)(*ldc_p);

    const auto op_a = (*transa == 'N' || *transa == 'n')
                      ? mtk::ozimmu::op_n : mtk::ozimmu::op_t;
    const auto op_b = (*transb == 'N' || *transb == 'n')
                      ? mtk::ozimmu::op_n : mtk::ozimmu::op_t;

    mtk::ozimmu::handle_t handle;
    mtk::ozimmu::create(&handle);

    mtk::ozimmu::reallocate_working_memory(handle, {
        {op_a, op_b, m, n, k,
         mtk::ozimmu::element_kind_t::real,
         mtk::ozimmu::compute_mode_t::fp64_int8_auto}
    });

    /* Apply beta scaling to C before the GEMM accumulation */
    if (*beta != 1.0) {
        const std::size_t size = ldc * n;
        if (*beta == 0.0) {
            std::memset(C, 0, size * sizeof(double));
        } else {
            for (std::size_t i = 0; i < size; i++) C[i] *= *beta;
        }
    }

    /* Use beta=1 now since we already applied it above */
    const double one = 1.0;
    mtk::ozimmu::gemm(
        handle,
        op_a, op_b,
        m, n, k,
        alpha, A, lda,
               B, ldb,
        &one,  C, ldc,
        mtk::ozimmu::compute_mode_t::fp64_int8_auto,
        mtk::ozimmu::element_kind_t::real
    );

    mtk::ozimmu::destroy(handle);
}

} /* extern "C" */
"""


def _write_wrapper_once(dest_dir: Path, lang: str) -> None:
    if lang == "fortran":
        for name, content in [("ozaki_wrapper.f90", _OZAKI_F90_WRAPPER),
                               ("ozaki_wrapper.cpp", _OZAKI_C_SHIM)]:
            out = dest_dir / name
            if not out.exists():
                out.write_text(content)
    else:
        out = dest_dir / "ozaki_wrapper.cpp"
        if not out.exists():
            out.write_text(_OZAKI_C_SHIM)


def _add_use_statement(lines: list[str], module: str) -> list[str]:
    """Insert 'use <module>' after the first 'implicit none' or program/subroutine/function line."""
    for i, line in enumerate(lines):
        if re.match(r"^\s*implicit\s+none\b", line, re.IGNORECASE):
            lines.insert(i, f"  use {module}\n")
            return lines
    for i, line in enumerate(lines):
        if re.match(r"^\s*(program|subroutine|function|module)\b", line, re.IGNORECASE):
            lines.insert(i + 1, f"  use {module}\n")
            return lines
    lines.insert(0, f"  use {module}\n")
    return lines


def _rewrite_fortran_dgemm(lines: list[str], hotspot: Hotspot) -> list[str]:
    """Replace CALL DGEMM(...) with CALL OZAKI_DGEMM(...)."""
    ln = hotspot.start_line - 1  # 0-indexed
    original = lines[ln]
    replaced = re.sub(r"\bDGEMM\s*\(", "OZAKI_DGEMM(", original, flags=re.IGNORECASE)
    lines[ln] = replaced
    lines = _add_use_statement(lines, "ozaki_wrapper")
    return lines


def _rewrite_fortran_loop(lines: list[str], hotspot: Hotspot) -> list[str]:
    """Replace a triple-nested FP64 DO loop with an ozIMMU DGEMM call.

    This is a best-effort transformation: we comment out the loop body and
    inject a DGEMM call.  For more complex cases a note is left for the user.
    """
    s = hotspot.start_line - 1
    e = hotspot.end_line  # exclusive (0-indexed end+1)

    # Extract loop variables and array names from the body
    body = "".join(lines[s:e])

    # Try to detect loop variables i,j,k and arrays A,B,C
    do_match = re.findall(r"do\s+(\w+)\s*=\s*1\s*,\s*(\w+)", body, re.IGNORECASE)
    acc_match = re.search(
        r"(\w+)\s*\(([^)]+)\)\s*=\s*\1\s*\(([^)]+)\)\s*\+\s*(\w+)\s*\(([^)]+)\)\s*\*\s*(\w+)\s*\(",
        body, re.IGNORECASE,
    )

    comment_block = ["! [try-ozaki] Original FP64 triple-nested loop — replaced by Ozaki DGEMM\n"]
    for line in lines[s:e]:
        comment_block.append("!" + line)

    if do_match and len(do_match) >= 3 and acc_match:
        c_arr = acc_match.group(1)
        a_arr = acc_match.group(4)
        b_arr = acc_match.group(6)
        dims = {v.lower(): dim for v, dim in do_match}
        n_var = list(dims.values())[0] if dims else "N"

        ozaki_call = [
            "! [try-ozaki] Ozaki DGEMM replacement (FP64 emulated via INT8 Tensor Cores)\n",
            f"  call OZAKI_DGEMM('N','N',{n_var},{n_var},{n_var},"
            f"1.0d0,{a_arr},size({a_arr},1),{b_arr},size({b_arr},1),"
            f"0.0d0,{c_arr},size({c_arr},1))\n",
        ]
    else:
        ozaki_call = [
            "! [try-ozaki] TODO: manual DGEMM replacement needed here\n",
            "! Loop pattern too complex for automatic extraction.\n",
        ]

    lines[s:e] = comment_block + ozaki_call
    lines = _add_use_statement(lines, "ozaki_wrapper")
    return lines


def _rewrite_c_dgemm(lines: list[str], hotspot: Hotspot) -> list[str]:
    ln = hotspot.start_line - 1
    original = lines[ln]
    replaced = re.sub(r"\bcblas_dgemm\s*\(", "ozaki_dgemm(", original)
    replaced = re.sub(r"\bDGEMM\s*\(", "ozaki_dgemm(", replaced, flags=re.IGNORECASE)
    lines[ln] = replaced
    # Ensure header is included
    has_include = any("ozaki_wrapper.h" in l for l in lines)
    if not has_include:
        lines.insert(0, '#include "ozaki_wrapper.h"\n')
    return lines


def rewrite(repo_dir: Path, hotspots: list[Hotspot]) -> list[Path]:
    """Apply Ozaki rewrites to all detected hotspots.

    Modifies files in-place (repo_dir should be a copy/clone).
    Returns list of modified file paths.
    """
    modified: set[Path] = set()
    written_wrappers: set[str] = set()

    # Group by file so we process line edits in order (bottom-up to preserve line numbers)
    from collections import defaultdict
    by_file: dict[Path, list[Hotspot]] = defaultdict(list)
    for h in hotspots:
        by_file[h.file].append(h)

    for file_path, hs in by_file.items():
        # Sort hotspots bottom-up so line number edits don't shift later ones
        hs_sorted = sorted(hs, key=lambda h: h.start_line, reverse=True)
        lines = file_path.read_text(errors="replace").splitlines(keepends=True)

        for h in hs_sorted:
            lang = h.language
            if lang == "fortran":
                if h.kind == "dgemm_call":
                    lines = _rewrite_fortran_dgemm(lines, h)
                elif h.kind == "loop_nest":
                    lines = _rewrite_fortran_loop(lines, h)
            elif lang in ("c", "cpp"):
                if h.kind in ("dgemm_call", "dgemv_call"):
                    lines = _rewrite_c_dgemm(lines, h)

            if lang not in written_wrappers:
                _write_wrapper_once(file_path.parent, lang)
                written_wrappers.add(lang)

        file_path.write_text("".join(lines))
        modified.add(file_path)

    return sorted(modified)
